### ISSUE TITLE
Can't Compile

### ISSUE THREAD

**Issue by nimafanniasl** [dusansimic/dynamic-wallpaper#12]
`Build started at 2022-05-01T20:23:39.783867
Main binary: /usr/bin/python3
Build Options: -Dprefix=/usr
Python system: Linux
The Meson build system
Version: 0.61.2
Source dir: /home/nima/dynamic-wallpaper
Build dir: /home/nima/dynamic-wallpaper/_build
Build type: native build
Project name: me.dusansimic.DynamicWallpaper
Project version: 0.0.1
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Configuring me.dusansimic.DynamicWallpaper.desktop.in using configuration
WARNING: Gettext not found, all translation targets will be ignored.
data/meson.build:10:0: ERROR: Can not assign None to variable.
`

**Comment by dusansimic** [comment]
Try installing the `gettext` package on your distribution. Which one are you running?

According to [this](https://gitlab.com/cunidev/gestures/-/issues/29) issue it seems that gettext needs to be installed so I'll add it as a build dependency.

**Comment by nimafanniasl** [comment]
I am in ubuntu :)

now my problem is "Run-time dependency gtk4 found: NO (tried pkgconfig and cmake)"

**Comment by dusansimic** [comment]
That's probably because you don't have GTK4 development files installed (on Ubuntu that might be libgtk-4-dev but I can't be sure). You'll need to install all dev dependencies for the app. You can find out which packages you're missing by putting the error that pops up into Google.

Also, I'd recommend building the app with flatpak if you're doing it of development purposes. It's the easiest way to do it and compatible on most of the popular distros. I'm using Gnome Builder for developing it since it also can build the app with flatpak.
