### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by TWB0109** [dusansimic/dynamic-wallpaper#17]
Not sure if it should go in here, but I'm willing to help translate the application to Spanish, I have no previous experience in doing so though.

**Comment by dusansimic** [comment]
Thanks for taking interest in this app and sorry for the slow reply. If you'd like to translate the app, I would recommend you do that in two steps.

You'll need to create a copy of the translation template file (`me.dusansimic.DynamicWallpaper.pot` in the `po` directory) and name it with the [two letter ISO language code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) which would in case of Spanish be `es.po`. Place it in the `po` directory with the rest of translations.

After that you'll need a software for editing po files. I use Gnome Translator since it's quite simple and lightweight. When you're done, send a pull request to add your translation.

To get more information regarding translation practices, you can contact the [Gnome Project Spanish translation team](https://l10n.gnome.org/teams/es/). The system for translating software in the Gnome project and other third party apps is a bit different but the translation process itself should be the same.

Let me know if you need any help!

**Comment by TWB0109** [comment]
Hi, Dušan:

Thank you for letting me collaborate with you, I will get hands on as soon
as I get off my day job.

Regards,
Brandon
